import Foundation

/// Represents a single speaker turn in the meeting transcript.
public struct DialogueTurnItem: Codable, Identifiable, Equatable, Sendable {
    public var id: String { "\(speaker)_\(text.hashValue)" }
    public let speaker: String
    public let text: String
    
    public init(speaker: String, text: String) {
        self.speaker = speaker
        self.text = text
    }
}

/// Primary structured payload generated by the on-device AI from the transcript.
public struct MeetingPayload: Codable, Equatable, Sendable {
    public let meetingSummary: String
    public let keyDecisions: [String]
    public let actionItems: [String]
    public let dialogueTurns: [DialogueTurnItem]
    public let calendarEvents: [CalendarEventItem]
    public let reminders: [ReminderItem]
    
    enum CodingKeys: String, CodingKey {
        case meetingSummary = "meeting_summary"
        case keyDecisions = "key_decisions"
        case actionItems = "action_items"
        case dialogueTurns = "dialogue_turns"
        case calendarEvents = "calendar_events"
        case reminders = "reminders"
    }
    
    public init(
        meetingSummary: String,
        keyDecisions: [String] = [],
        actionItems: [String] = [],
        dialogueTurns: [DialogueTurnItem] = [],
        calendarEvents: [CalendarEventItem] = [],
        reminders: [ReminderItem] = []
    ) {
        self.meetingSummary = meetingSummary
        self.keyDecisions = keyDecisions
        self.actionItems = actionItems
        self.dialogueTurns = dialogueTurns
        self.calendarEvents = calendarEvents
        self.reminders = reminders
    }
}

/// Extracted calendar event ready for EventKit transformation.
public struct CalendarEventItem: Codable, Identifiable, Equatable, Sendable {
    public var id: String { "\(title)_\(date)_\(time)" }
    public let title: String
    public let date: String       // Format: YYYY-MM-DD
    public let time: String       // Format: HH:MM AM/PM
    public let attendees: [String]
    
    public init(title: String, date: String, time: String, attendees: [String] = []) {
        self.title = title
        self.date = date
        self.time = time
        self.attendees = attendees
    }
    
    /// Parses the date and time strings into a concrete Swift Date object.
    public func targetStartDate(timeZone: TimeZone = .current) -> Date? {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd hh:mm a"
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = timeZone
        return formatter.date(from: "\(date) \(time)")
    }
}

/// Extracted reminder task ready for EventKit EKReminder transformation.
public struct ReminderItem: Codable, Identifiable, Equatable, Sendable {
    public var id: String { "\(title)_\(dueDate)_\(time)" }
    public let title: String
    public let dueDate: String    // Format: YYYY-MM-DD
    public let time: String       // Format: HH:MM AM/PM
    
    enum CodingKeys: String, CodingKey {
        case title
        case dueDate = "due_date"
        case time
    }
    
    public init(title: String, dueDate: String, time: String) {
        self.title = title
        self.dueDate = dueDate
        self.time = time
    }
    
    /// Parses the due date and time strings into a concrete Swift Date object.
    public func targetDueDate(timeZone: TimeZone = .current) -> Date? {
        let formatter = DateFormatter()
        formatter.dateFormat = "yyyy-MM-dd hh:mm a"
        formatter.locale = Locale(identifier: "en_US_POSIX")
        formatter.timeZone = timeZone
        return formatter.date(from: "\(dueDate) \(time)")
    }
}
